### ISSUE TITLE
Change UI colors for readability

### ISSUE THREAD

**Issue by appleparan** [minmul117/vscode-sublette#11]
Some UI color such as `list.activeSelectionBackground` hurts readability.

Let's gather examples and fix at once.

* Solution List
1. `activityBar.foreground` would be fixed by Foreground(#ccced0) or White(#f5f5da)
2. I would like to use Dim Blue(`#347`) instead of Blue(`#587`), How about your opinion?

* List of hard to read examples
- [ ] all Blue(`#587`) background colors in UI.   `list.activeSelectionBackground` 
![list.activeSelectionBackground](https://user-images.githubusercontent.com/156580/60319719-56bd8480-99b2-11e9-906e-9e2265db1eea.png)

- [ ] `activityBar.foreground`
![activityBar.foreground](https://user-images.githubusercontent.com/156580/60319910-0a267900-99b3-11e9-9dfd-501f3ea62a28.png)

**Comment by sublee** [comment]
I agree with you. Check #12.

**Comment by appleparan** [comment]
Seems to be fixed.
