### ISSUE TITLE
Specify the license

### ISSUE THREAD

**Issue by sublee** [minmul117/vscode-sublette#14]
This project doesn't specify the license yet. @minmul117 the owner should choose one in https://choosealicense.com/ and add a proper `LICENSE` file. `package.json` also should be modified to export the license.

**Comment by minmul117** [comment]
Thanks for your suggestion! I will choose MIT License, same as Sublette.

**Comment by minmul117** [comment]
https://github.com/minmul117/vscode-sublette/pull/15

**Comment by appleparan** [comment]
You can use keywords like `close` on PR or commit to close the issue. Here is [link](https://help.github.com/en/articles/closing-issues-using-keywords)
