### ISSUE TITLE
Not to trigger Travis CI build on PR

### ISSUE THREAD

**Issue by appleparan** [minmul117/vscode-sublette#9]
Current Travis CI setup is only for publishing VS code extension. It doesn't need to be triggered on every PR and this always fail because of `$PUBLISHER_KEY`.

Please turn off Travis build on PR

**Comment by minmul117** [comment]
@appleparan Sorry for your inconvenience. Actually, this is my first time to use Travis CI, and I didn't expect that other people will give pull request. 

After the pull requests which currently opened finish, I will turn off Travis immediately and fix it.
Thanks!

**Comment by appleparan** [comment]
You don't need to wait. I think there is two way to do this.

1. [Use .travis.yml](https://docs.travis-ci.com/user/pull-requests/)
2. Turn off Build pushed pull requests in repo setting
![Travis CI setting](https://user-images.githubusercontent.com/156580/60318201-16a7d300-99ad-11e9-857c-08c0009cb410.png)

In my opinion, you should turn off build pushed branches, either. You don't need to publish extension on every your push.

**Comment by minmul117** [comment]
Currently, my travis dashboard goes wrong (I think it is bug maybe), and the dashboard cannot find and sync this repository. I was very embarassed because I used the dashboard yesterday.

I changed .travis.yml, so it will be build when base branch is `tag` in PR.

**Comment by appleparan** [comment]
Solved
